In [8]:
import numpy as np

np.random.seed(114514)
print(np.random.normal(0. ,1. , (3,3)))
print(np.random.normal(0. ,1. , (3,3)))

[[ 1.11490901  1.1882115   1.41804512]
 [-0.36769038  0.24881411  0.38049812]
 [ 0.6352939  -1.09419838  0.44031896]]
[[-0.84903172  1.5081906  -0.68171421]
 [ 0.06852704 -0.57467491 -0.53778764]
 [-0.60896204 -0.64299123  0.23048472]]
